import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:moneywise/data/model/category.dart';
import 'package:moneywise/data/repo/category_repo_firestore.dart';
import 'package:moneywise/theme/app_colors.dart';
import 'package:moneywise/utils/color_utils.dart';
import 'package:moneywise/utils/category_constants.dart';

class CategoryManageScreen extends StatefulWidget {
  final String? categoryId;
  const CategoryManageScreen({super.key, this.categoryId});

  @override
  State<CategoryManageScreen> createState() => _CategoryManageScreenState();
}

class _CategoryManageScreenState extends State<CategoryManageScreen> {
  final categoryRepo = CategoryRepoFirestore();
  final TextEditingController _nameController = TextEditingController();

  bool _isLoading = true;
  bool _isSubmitting = false;
  Category? _category;
  String _selectedType = 'expense';
  String? _selectedIcon;
  String _selectedColor = 'blue';

  @override
  void initState() {
    _loadData();
    super.initState();
  }

  Future<void> _loadData() async {
    setState(() {
      _isLoading = true;
    });

    try {
      if (widget.categoryId != null) {
        await _loadCategoryData();
      } else {
        // Set defaults for new category
        _selectedIcon = CategoryConstants.availableIcons.values.first;
        setState(() {
          _isLoading = false;
        });
      }
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Error loading data: $e')));
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _loadCategoryData() async {
    try {
      _category = await categoryRepo.getCategoryById(widget.categoryId!);
      if (_category != null) {
        _nameController.text = _category!.name;
        _selectedType = _category!.type;
        _selectedIcon = _category!.icon;
        _selectedColor = _category!.color;
      }
      setState(() {
        _isLoading = false;
      });
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Error loading category: $e')));
      setState(() {
        _isLoading = false;
      });
    }
  }

  Future<void> _submitCategory() async {
    if (_nameController.text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please enter a category name')),
      );
      return;
    }

    if (_selectedIcon == null) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Please select an icon')));
      return;
    }

    setState(() {
      _isSubmitting = true;
    });

    try {
      if (widget.categoryId != null) {
        // Update existing category
        final updatedCategory = Category(
          id: _category!.id,
          name: _nameController.text,
          type: _selectedType,
          icon: _selectedIcon!,
          color: _selectedColor,
        );
        await categoryRepo.updateCategory(updatedCategory);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Category updated successfully')),
        );
      } else {
        // Create new category
        final newCategory = Category(
          id: '', // Will be generated by Firestore
          name: _nameController.text,
          type: _selectedType,
          icon: _selectedIcon!,
          color: _selectedColor,
        );
        await categoryRepo.addCategory(newCategory);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Category created successfully')),
        );
      }
      context.pop();
    } catch (e) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Error saving category: $e')));
    } finally {
      setState(() {
        _isSubmitting = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEdit = widget.categoryId != null;
    final title = isEdit ? 'Edit Category' : 'Add Category';
    final buttonColor =
        _selectedType == 'income' ? AppColors.income : AppColors.expense;

    return Scaffold(
      appBar: AppBar(
        title: Text(title),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => context.pop(),
        ),
      ),
      body:
          _isLoading
              ? const Center(child: CircularProgressIndicator())
              : SingleChildScrollView(
                padding: const EdgeInsets.all(16.0),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Category Name Field
                    TextField(
                      controller: _nameController,
                      decoration: const InputDecoration(
                        labelText: 'Category Name',
                        border: OutlineInputBorder(),
                        prefixIcon: Icon(Icons.category),
                      ),
                    ),
                    const SizedBox(height: 16.0),

                    // Category Type Selector
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'Category Type',
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        const SizedBox(height: 10),
                        Row(
                          children: [
                            Expanded(
                              child: RadioListTile<String>(
                                title: const Text('Expense'),
                                value: 'expense',
                                groupValue: _selectedType,
                                onChanged: (value) {
                                  if (value != null) {
                                    setState(() {
                                      _selectedType = value;
                                    });
                                  }
                                },
                                activeColor: AppColors.expense,
                              ),
                            ),
                            Expanded(
                              child: RadioListTile<String>(
                                title: const Text('Income'),
                                value: 'income',
                                groupValue: _selectedType,
                                onChanged: (value) {
                                  if (value != null) {
                                    setState(() {
                                      _selectedType = value;
                                    });
                                  }
                                },
                                activeColor: AppColors.income,
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                    const SizedBox(height: 16.0),

                    // Icon Selector
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'Select Icon',
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        const SizedBox(height: 10),
                        Container(
                          constraints: const BoxConstraints(maxHeight: 200),
                          decoration: BoxDecoration(
                            border: Border.all(color: Colors.grey.shade300),
                            borderRadius: BorderRadius.circular(8),
                          ),
                          child: GridView.builder(
                            padding: const EdgeInsets.all(8),
                            shrinkWrap: true,
                            physics: const AlwaysScrollableScrollPhysics(),
                            gridDelegate:
                                SliverGridDelegateWithFixedCrossAxisCount(
                                  crossAxisCount:
                                      MediaQuery.of(context).size.width > 600
                                          ? 6
                                          : 4,
                                  crossAxisSpacing: 12,
                                  mainAxisSpacing: 12,
                                ),
                            itemCount: CategoryConstants.availableIcons.length,
                            itemBuilder: (context, index) {
                              final iconEntry = CategoryConstants
                                  .availableIcons
                                  .entries
                                  .elementAt(index);
                              final iconPath = iconEntry.value;
                              final iconName = iconEntry.key;
                              final isSelected = _selectedIcon == iconPath;
                              final selectedColor = getColorFromString(
                                _selectedColor,
                              );

                              return GestureDetector(
                                onTap: () {
                                  setState(() {
                                    _selectedIcon = iconPath;
                                  });
                                },
                                child: Container(
                                  decoration: BoxDecoration(
                                    border: Border.all(
                                      color:
                                          isSelected
                                              ? selectedColor
                                              : Colors.grey.shade300,
                                      width: 2,
                                    ),
                                    borderRadius: BorderRadius.circular(8),
                                    color:
                                        isSelected
                                            ? selectedColor.withAlpha(30)
                                            : null,
                                  ),
                                  child: Column(
                                    mainAxisAlignment: MainAxisAlignment.center,
                                    children: [
                                      Image.asset(
                                        iconPath,
                                        width: 24,
                                        height: 24,
                                        color:
                                            isSelected
                                                ? selectedColor
                                                : Colors.grey.shade600,
                                        errorBuilder: (
                                          context,
                                          error,
                                          stackTrace,
                                        ) {
                                          return Icon(
                                            Icons.category,
                                            color:
                                                isSelected
                                                    ? selectedColor
                                                    : Colors.grey.shade600,
                                            size: 24,
                                          );
                                        },
                                      ),
                                      const SizedBox(height: 4),
                                      Text(
                                        iconName,
                                        style: TextStyle(
                                          fontSize: 8,
                                          color:
                                              isSelected
                                                  ? selectedColor
                                                  : Colors.grey.shade600,
                                        ),
                                        textAlign: TextAlign.center,
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ],
                                  ),
                                ),
                              );
                            },
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16.0),

                    // Color Selector
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'Select Color',
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        const SizedBox(height: 10),
                        Wrap(
                          spacing: 12,
                          runSpacing: 12,
                          children:
                              [
                                'red',
                                'pink',
                                'purple',
                                'blue',
                                'cyan',
                                'teal',
                                'green',
                                'lime',
                                'yellow',
                                'orange',
                                'brown',
                                'grey',
                              ].map((colorName) {
                                final color = getColorFromString(colorName);
                                final isSelected = _selectedColor == colorName;

                                return GestureDetector(
                                  onTap: () {
                                    setState(() {
                                      _selectedColor = colorName;
                                    });
                                  },
                                  child: Container(
                                    width: 50,
                                    height: 50,
                                    decoration: BoxDecoration(
                                      color: color,
                                      shape: BoxShape.circle,
                                      border: Border.all(
                                        color:
                                            isSelected
                                                ? Colors.black
                                                : Colors.grey.shade300,
                                        width: isSelected ? 3 : 1,
                                      ),
                                    ),
                                    child:
                                        isSelected
                                            ? const Icon(
                                              Icons.check,
                                              color: Colors.white,
                                              size: 24,
                                            )
                                            : null,
                                  ),
                                );
                              }).toList(),
                        ),
                      ],
                    ),
                    const SizedBox(height: 24.0),

                    // Submit Button
                    SizedBox(
                      width: double.infinity,
                      height: 50,
                      child: ElevatedButton(
                        onPressed: _isSubmitting ? null : _submitCategory,
                        style: ElevatedButton.styleFrom(
                          backgroundColor: buttonColor,
                          foregroundColor: Colors.white,
                        ),
                        child:
                            _isSubmitting
                                ? const CircularProgressIndicator(
                                  color: Colors.white,
                                )
                                : Text(
                                  isEdit ? 'Update Category' : 'Add Category',
                                ),
                      ),
                    ),
                  ],
                ),
              ),
    );
  }
}
